const data = {
  products: [
    {
      name: 'Checker',
      slug: 'checker',
      category: 'checker',
      image: '/resources/checker.jpg',
      price: 120,
      brand: 'curtain foam',
      rating: 4.5,
      numReviews: 16,
      countInStock: 10,
      description: 'This good and get it in affordable price',
    },
    {
      name: 'Cresendo',
      slug: 'cresendo',
      category: 'cresendo',
      image: '/resources/cresendo.jpg',
      price: 200,
      brand: 'curtain steel',
      rating: 5,
      numReviews: 23,
      countInStock: 20,
      description: 'Buy it you dont regret cuz its smooth and nicely in your eyes',
    },
    {
      name: 'Curves',
      slug: 'curves',
      category: 'curves',
      image: '/resources/curves.jpg',
      price: 100,
      brand: 'curtain wood',
      rating: 4,
      numReviews: 12,
      countInStock: 35,
      description: 'If you wanted  wood display this is fit for you',
    },

    {
      name: 'Izmir',
      slug: 'izmir',
      category: 'izmir',
      image: '/resources/izmir.jpg',
      price: 120,
      brand: 'curtain flex',
      rating: 4.5,
      numReviews: 8,
      countInStock: 10,
      description: 'This good and get it in affordable price',
    },

    {
      name: 'Linen',
      slug: 'linen',
      category: 'linen',
      image: '/resources/linen.jpg',
      price: 110,
      brand: 'curtain white wood',
      rating: 4.5,
      numReviews: 6,
      countInStock: 32,
      description: 'Finding a neat and nicer look this best for you',
    },

    {
      name: 'Mono',
      slug: 'mono',
      category: 'mono',
      image: '/resources/mono.jpg',
      price: 110,
      brand: 'curtain brown wood',
      rating: 3,
      numReviews: 5,
      countInStock: 21,
      description: 'simple but amazing design',
    },

    {
      name: 'Pinova',
      slug: 'pinova',
      category: 'pinova',
      image: '/resources/pinova.jpg',
      price: 170,
      brand: 'curtain foam',
      rating: 5,
      numReviews: 10,
      countInStock: 50,
      description: 'This good and get it in affordable price',
    },

    {
      name: 'Pleast and Twist',
      slug: 'pleast-twist',
      category: 'pleastandtwist',
      image: '/resources/pleastandtwist.jpg',
      price: 190,
      brand: 'curtain straw',
      rating: 5,
      numReviews: 34,
      countInStock: 40,
      description: 'A plastic display design a better look in our eyes',
    },

    {
      name: 'Silk',
      slug: 'silk',
      category: 'silk',
      image: '/resources/silk.jpg',
      price: 150,
      brand: 'curtain wood',
      rating: 4.5,
      numReviews: 23,
      countInStock: 15,
      description: 'If you thinking its a shampoo your wrong its a wood curtain design',
    },
  ],
};

export default data;
